### ISSUE TITLE
Cannot Reproduce Results on hyper_kg

### ISSUE THREAD

**Issue by Xiao9905** [amazon-research/hyperbolic-embeddings#4]
Hi @Akirato @nikrao ,

Thanks for your great work on HypE! However, I have been trying to reproduce your excellent results on FB15k-237, but to find the hyper-parameters you have provided in `example_hype.sh` to be the same for all default datasets. The consequent results are much poorer than your report.

Could you please provide the reproducible hyper-parameters in the `example_hype.sh`? Thanks again for your help.

**Comment by Xiao9905** [comment]
Hi @Akirato ,

Thanks for your reply! Actually I am working on the same data split of FB15k-237 from Query2Box (also the same as yours, if I understand correctly), and find your HypE's performance really impressive. So I would like to repeat exactly the same experiment you have reported in your paper for the consideration of case study.

**Comment by Xiao9905** [comment]
@Akirato  It would be appreciated if you can also provide hyper-params for NELL995 and FB15k as is in your paper. Thanks for your great help!

**Comment by Akirato** [comment]
Hi @Xiao9905 ,

Just an update, I am working on it and have found the resolution (right hyperparameters and some corrections in the manifold operations). However, its taking me sometime to rerun and evaluate the model on the q2b datasets. I should be able to post the resolution by mid next week. Hope that is good!

**Comment by Xiao9905** [comment]
Hi @Akirato ,

Sure, that's great! Waiting for your good news.

**Comment by zhiweihu1103** [comment]
It was also difficult for me to reproduce the results in the HypE paper.

**Comment by Akirato** [comment]
Hello,

Unfortunately, the issue is that I don't have access to the exact dataset (the difference between q2b and hype dataset is the addition of reverse links but the sampling was random, so I have to figure it out) that I was using in the experiments. So, I am trying two things;
1. Recreate the dataset used in our paper and optimize the hyper-parameters.
2. Optimize the hyper-parameters for the q2b dataset for best performance.
On 1, I am not sure if I would be able to do it fast because it requires several experiments, but I will continue on it. On 2, I have already found good results with performance close to 10% better than q2b on the same sample available [here](https://github.com/hyren/query2box), which would be good for any comparison between q2b and hype. However, I am trying to optimize them for the best results possible. I am running the last set of experiments to be sure of no errors. I will share both the code and my logs for the same as soon as I am done. Thanks a lot for your patience 😄

**Comment by Xiao9905** [comment]
Thanks for your great work! Waiting for your progress.

**Comment by Akirato** [comment]
Hello,

Thanks a lot for your patience. I have finished the parameter tuning for Q2B dataset and posted the repo here; 
[https://github.com/Akirato/HypE ](https://github.com/Akirato/HypE )
You can find my logs here: [https://www.dropbox.com/sh/v3x478ku8ajrsof/AACI2sV1tLGB0FhWTNrN4-VNa?dl=0](https://www.dropbox.com/sh/v3x478ku8ajrsof/AACI2sV1tLGB0FhWTNrN4-VNa?dl=0)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/nurendrachoudhary/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/nurendrachoudhary/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



  | 1t | 2t | 3t | 2i | 3i | 2u | ic | ci | uc
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
FB15k | 0.704 | 0.474 | 0.372 | 0.516 | 0.619 | 0.514 | 0.265 | 0.393 | 0.412
FB15k-237 | 0.562 | 0.342 | 0.272 | 0.364 | 0.459 | 0.352 | 0.165 | 0.252 | 0.295
NELL | 0.572 | 0.388 | 0.282 | 0.408 | 0.522 | 0.45 | 0.197 | 0.284 | 0.284



</body>

</html>

The code hasn't been tested on different machines. So, if possible, please send me your system configuration and train.log files on nurendra[at]vt[dot]edu so I can skip some steps.

**Comment by zhiweihu1103** [comment]
Thank you very much for your efforts, I will reproduce the code.

**Comment by zhiweihu1103** [comment]
Further questions：

**Comment by Akirato** [comment]
Hi @zhiweihu1103 ,

1. When we were experimenting for the paper, we didn't have access to the actual dataset, so we had to get the dataset construction script from the authors (now available [here](https://github.com/snap-stanford/KGReasoning/blob/main/create_queries.py)). The script involves random sampling and hence the sample we got is different and hence, produces different results.
2. The data provided on the link is exactly the same as the Q2B paper. In there, I have tuned the model to the exact Q2B dataset (due to popular demand).

**Comment by zhiweihu1103** [comment]
Hi @Akirato. What I want to ask is why there is a big difference between the effect and the paper on the dataset provided by Q2B, because as you said, you are using the same dataset as Q2B.

**Comment by Akirato** [comment]
> Hi @Akirato. What I want to ask is why there is a big difference between the effect and the paper on the dataset provided by Q2B, because as you said, you are using the same dataset as Q2B.

Both the Q2B paper and HypE paper use the same dataset but different subsamples of it, generated using the script.

**Comment by zhiweihu1103** [comment]
Did you regenerate 1p, 2p and other query structure data on FB15k based on the create_queries.py code? Why not directly use the already generated 1p, 2p and other query structure data provided by Q2B?(https://github.com/hyren/query2box/tree/master/data) Because I see your code is based on the Q2B repository.

**Comment by Akirato** [comment]
> Did you regenerate 1p, 2p and other query structure data on FB15k based on the create_queries.py code? Why not directly use the already generated 1p, 2p and other query structure data provided by Q2B?(https://github.com/hyren/query2box/tree/master/data) Because I see your code is based on the Q2B repository.

That was just a matter of choice. I couldn't understand what their data folder actually contained, which I needed to know to create the same format for the other datasets. So, I just got the file from them and created the samples on my own. But, in hindsight, I could have just gone for their version for the given datasets.

**Comment by zhiweihu1103** [comment]
ok, thanks for your patience in explaining.

**Comment by Akirato** [comment]
> ok, thanks for your patience in explaining.

No issues there. Please send me your system configuration and log files at nurendra[at]vt[dot]edu 😄
